workspace:
  base: /go
  path: src/

pipeline:
  pull-from-ecr:
    image: lpf190/drone-pull-ecr:v0.01
    pull: true
    priviteged: true
    environment:
      - AWS_ACCESS_KEY_ID=ecr_access_key
      - AWS_SECRET_ACCESS_KEY=ecr_secret_key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - $(aws ecr get-login --no-include-email --region ap-northeast-1)
      - docker pull 376045331903.dkr.ecr.ap-northeast-1.amazonaws.com/play-web/fish:v0.08
